### ISSUE TITLE
Usage of Div

### ISSUE THREAD

**Issue by JohnCoene** [tyluRp/vov#3]
Wouldn't something like the snippet below be more convenient?

```r
fade_in_bottom_right <- function(..., duration = NULL, delay = NULL) {
  x <- parse_animation("fade-in-bottom-right", duration, delay)
  htmltools::tagAppendAttributes(x, class = x)
}
```

In the event I want to put an effect on say a `<span>` within a paragraph or on a column, the `<div>` would break things.

Perhaps the reason behing using `<div>` escapes me.

**Comment by tylerlittlefield** [comment]
Hm, I will give it a try this afternoon. I don’t have a great reason for using `div`, it’s just the first way I got it to work. Thank you for the suggestion!

**Comment by tylerlittlefield** [comment]
Thanks again for the suggestion, vov now uses `htmltools::tagAppendAttributes`. Additionally, I have replaced `...` with `ui`, for each animation call you can only supply a single UI.

Also, love `waiter`, I use it at work 😄

**Comment by JohnCoene** [comment]
Thanks! 😃
