### ISSUE TITLE
Joint use of fade_in and fade_out

### ISSUE THREAD

**Issue by Jimbilben** [tyluRp/vov#5]
I'm struggling to understand how to use the vov functions in all the but the most basic ways. For example, the following conditional panel would fade in when the condition is met. But is it possible make the panel fade in when called, and to fade back out when the condition is no longer met? I can't see how to wrap it in both fade in and fade out:
```

conditionalPanel(
      condition = "input.condition == true",
      fade_in(
      sliderInput("name",
                  label = "Label",
                  min = -1,
                  max = 1),
      duration = "fast", delay = 0, steps = 10, iteration = 1
      ))
```

**Comment by tylerlittlefield** [comment]
Is this what you're trying to do?
```r
library(shiny)
library(vov)

ui <- fluidPage(
  use_vov(),
  uiOutput("text"),
  selectInput("animation", "Animation", choices = c("fade-in-left", "fade-out-right"))
)

server <- function(input, output, session) {
  animation <- reactive({
    input$animation
  })
  
  output$text <- renderUI({
    switch (animation(),
      "fade-in-left" = vov::fade_in_left(tags$div("hello!")),
      "fade-out-right" = vov::fade_out_right(tags$div("goodbye!")),
    )
  })
}

shinyApp(ui, server)
```

**Comment by tylerlittlefield** [comment]
Additionally, there is also [`vov::run_demo()`](https://vov-pkg.netlify.app/reference/run_demo.html) which is an app that conditionally generates animations based on inputs.

**Comment by Jimbilben** [comment]
Thanks for your quick response @tyluRp - I will try to implement something like this in my code and see how it goes!

**Comment by tylerlittlefield** [comment]
No problem! I will close this for now, but if things still aren't working as expected let me know and I'll reopen 👍🏻
